#-------- Local match definition --------
error_rates = [0, 0.025, 0.05]
min_len = 100

#-------- Valik parameters --------
fpr = 0.01
bins = config["ibf_bins"]
max_capacity = config["cart_max_capacity"]
max_carts = config["max_queued_carts"]

sort_thresh = 5000
num_matches = 5001

#--------\ Shared functions --------
import random
import math

#-------- Shared functions \--------

rule make_all:
	input:
		expand("stellar_er{er}.gff", er = error_rates),	
		expand("valik_er{er}.gff", er = error_rates),
		"blast.tsv"
	shell:
		"echo 'Done'"

include: "rules/prepare.smk"
include: "rules/dream.smk"
include: "rules/stellar.smk"
include: "rules/blast.smk"
