configfile: "config.yaml"

error_rates = ["0", "0025", "005", "0075", "01"]
min_len = config["min_len"]

rule make_all:
	input:
		"table1.tsv"
	shell:
		"echo 'Done'"

include: "rules/simulate.smk"
include: "rules/stellar.smk"
include: "rules/evaluate.smk"

