n = config["repeat"]
repetitions = list(range(n))
error_rates = config["er_rates"]
min_len = config["min_len"]

workdir: config['workdir']

rule make_all:
	input:
		"table1.tsv"
	shell:
		"echo 'Done'"

include: "rules/simulate.smk"
include: "rules/stellar.smk"
include: "rules/evaluate.smk"

